### ISSUE TITLE
Error in generating Exo data object - Error: subscript contains invalid names

### ISSUE THREAD

**Issue by ghost** [welch16/ChIPexoQual#7]
Hello,
I am new in the field of data analysis and this is first time I am using R. I am trying to generate Exo data object and every time I am getting following error:

> SM001A = ExoData(reads = ex, mc.cores = 2L, verbose = TRUE)
Using 'reads' argument
Keeping reads in object: No
Error: subscript contains invalid names
> 
I am stuck at this error for almost a week now. Please help!

**Comment by welch16** [comment]
Hi @VS128,

I think I have seen this error before, if you do the following:

```
library(tidyverse)

dt = reads %>% 
  DataFrame() %>% as.data.frame() %>% 
  as_tibble()

dt %>% 
  group_by(seqnames) %>% 
  summarize(n = n()) %>% 
  arrange(-n)%>% 
  head(20) %>% 
  ggplot(aes(reorder(seqnames,n),n))+geom_col()+
           coord_flip()
```

you will notice that there are some chromosomes with a very low sequencing depth compared to the rest. This occurs because sometimes the genomes reference files contain additional chromosome besides the usual ones. You just need to remove the reads aligned to those chromosomes, as in later steps of the pipeline when the coverage is partitioned, there is not enough sequencing depth to do so.
